### ISSUE TITLE
Nice project - few questions

### ISSUE THREAD

**Issue by abhishekgahlot2** [xogoodnow/Clickhouse_Cluster#2]
Really nice project, trying to do something similar with aws.

what is victoria metrics being used here for?

**Comment by xogoodnow** [comment]
Thank you @abhishekgahlot2,
I decided to setup a monitoring stack with Victoriametrics to monitor the cluster.
When the cluster is setup the monitoring stack comes up as well and when I run the benchmark script, I can monitor the cluster performance with different configurations.
If there was anything that I could help you with let me know.

**Comment by abhishekgahlot2** [comment]
Gotcha, I am migrating the repo to aws, and almost half way there. Was able to spin up instances and launch docker from ansible. 

Some changes I did are using `ubuntu` as user for root and allow ansible to become sudo for installing packages?

Would you be willing to accept a pr for aws too if i raised? may be in separate folder with different terraform plan.

Some more questions actually?

1. Since in aws I might have to add a load balancer, which clickhouse node should be added to the load balancer. i think all the nodes should be added load balancer.
2. Can zookeeper instance size be much smaller since its for only metadata tracking.
3. Also looks like you are using self signed certificate but the load balancer will have different AWS-issued SSL. 

Thanks again for the help :)

Also this is the most sensible project out there on whole github I tried searching a lot,  this can actually launch ch cluster on production level. You might wanna create an organization out of it (just an idea )

**Comment by xogoodnow** [comment]
1. Sure, It would be great to add it (AWS terraform).
2. You must add all the nodes to the stack. keep in mind that if you are using a weighting system for load balancing, set the same weight for all nodes. Clickhouse would load balance itself, just introduce them all to the load balancer equally.
3. The certificate that ansible  issues is for internal and external use of ClickHouse, it would be possible to use other certificates with a valid issuer but I believe we would be able to use a self signed cert on the load balancer as well. (If the load balancer is layer 4, it would not require the certs (I think))
4. Yes but not too small. in my experience you can have it on the same node as ClickHouse but if you want to launch a separate instance for it I believe 2core 2g would be sufficient for a medium sized cluster with a normal load, but if its larger you might require some more processing power than 2 cores. 

I appreciate your kind feedback, that would be a great idea but the project could become much more mature before turning it into an Org.
I would appreciate your help to make it happen. 

Glad to be of any help.

**Comment by abhishekgahlot2** [comment]
Thanks again for the reply. I want to open some more bug report in private issues, My migration is done so raising issues.

**Comment by xogoodnow** [comment]
Sure
