### ISSUE TITLE
Clickhouse cluster node 2 and node 3 becomes unresponsive after first install

### ISSUE THREAD

**Issue by abhishekgahlot2** [xogoodnow/Clickhouse_Cluster#3]
For eg i have to restart node 2 and node 3 to get it working or be able to connect to.

I checked even though the docker is running somehow the port used by docker 9440 is not being occupied. 

When i checked with `netstat -nl` i saw no port registered by clickhouse which is 9440 and 8443

After i restart docker this goes away.

**Comment by xogoodnow** [comment]
Yes you are right.
I'll check it

**Comment by xogoodnow** [comment]
Fixed the issue.
Feel free to test it and sorry for the late response
@abhishekgahlot2
