### ISSUE TITLE
Specify the clickhouse and keeper version in vars.yaml

### ISSUE THREAD

**Issue by abhishekgahlot2** [xogoodnow/Clickhouse_Cluster#7]
I just deployed new cluster and lots of changes are broken. I think it would be good to specify version in vars.yaml

Just an idea or support new clickhouse feature with latest tag.

**Comment by xogoodnow** [comment]
hi @abhishekgahlot2,
Sorry for the delay in response, made the changes.
Hope it would be useful to you
